### ISSUE TITLE
Accordion the Sections

### ISSUE THREAD

**Issue by antheas** [hhd-dev/hhd-decky#2]
Each hhd settings section should get its own panel in Decky.

A section is designed to host self-contained settings (such as TDP, controllers, RGB, misc settings). It does not make sense for them to be in the same scrolling page.

Since the UI in decky is limited, that can be accomplished with a dropdown component on the top that is styled differently, this component allows switching between sections.

Since sections do not have names, they can be hardcoded for now and if one does not exist, the first letter of the section code can be capitalized (`controller -> Controller`). 

Although there should be an endpoint in the future that returns them (*cough* localization).

**Comment by aarron-lee** [comment]
resolved for now by adding per-container toggles to show/hide them

![image](https://github.com/hhd-dev/hhd-decky/assets/9145965/4d9570bc-962e-4111-8c10-c12edceec16d)
![image](https://github.com/hhd-dev/hhd-decky/assets/9145965/f973b4ae-5951-4776-ae37-70c7b0973d01)
