### ISSUE TITLE
[Feature Request] Bundle Updater into Decky

### ISSUE THREAD

**Issue by antheas** [hhd-dev/hhd-decky#3]
The decky updater is built into hhd currently which is not ideal.

Instead, the decky plugin itself should update when a button with the tag `hhd-update-decky` is pressed. The action should not be then sent to hhd.

In addition, when there is a crash in the decky plugin, instead of displaying `Something went wrong` with broken margins, it should present two buttons: one to refresh the UI, and one to update the plugin.

**Comment by aarron-lee** [comment]
@antheas For the Decky plugin Update, would you like me to build it into hhd-decky, and remove you can it from hhd altogether? I can just replicate what I've done for other decky plugins

**Comment by antheas** [comment]
That'd be great

**Comment by aarron-lee** [comment]
released in v0.0.8

![image](https://github.com/hhd-dev/hhd-decky/assets/9145965/0fc2b7d1-2888-4ded-b5fa-fc03f331c5bc)
