### ISSUE TITLE
[feature request] Implement hints correctly

### ISSUE THREAD

**Issue by antheas** [hhd-dev/hhd-decky#7]
Right now, there are some settings that arbitrarily show hints and some settings that dont.

The setting that does is the mode setting, all others do not.

Implement hints universally so that all of them are accessible from the ui. Consider allocating the bottom section of the screen for them. So as you scroll through the settings the hints change.

**Comment by aarron-lee** [comment]
one feature i've been meaning to investigate is to have a hint appear when the element in question is focused. haven't investigated it yet, but should be possible. thoughts?

**Comment by antheas** [comment]
I would rather it appear in the bottom or on the side, I think making it appear on hover may be disorienting.

**Comment by aarron-lee** [comment]
added hints to other inputs and fields
